// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXXLW78tEy9xzoKAvYZVB-hTsIb0Y6lus',
    appId: '1:1069385576634:web:fa4f7c460215a7abe61283',
    messagingSenderId: '1069385576634',
    projectId: 'groceryapp-c7695',
    authDomain: 'groceryapp-c7695.firebaseapp.com',
    storageBucket: 'groceryapp-c7695.appspot.com',
    measurementId: 'G-JR2JQYKXQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgdbrIgJxGtpMrkt1WioZutMf6yuPAgVo',
    appId: '1:1069385576634:android:0fa5337331ceb75be61283',
    messagingSenderId: '1069385576634',
    projectId: 'groceryapp-c7695',
    storageBucket: 'groceryapp-c7695.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdiE1ZcShhV8aLPV_cY2HPpv6Z_vwh344',
    appId: '1:1069385576634:ios:da11ba8573b8d86be61283',
    messagingSenderId: '1069385576634',
    projectId: 'groceryapp-c7695',
    storageBucket: 'groceryapp-c7695.appspot.com',
    iosClientId: '1069385576634-lmc25307mgsjeoh1gmdt8g341vs8mpc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineGroceryAppUi',
  );
}
